import type { Lang } from '../types'

export const ui = {
  fr: {
    offre: 'Offre',
    trajet: 'Trajet',
    villes: 'Villes',
    agence: 'Agence',
    devis: 'Devis',
    whatsapp: 'WhatsApp',
    langFr: 'FR',
    langAr: 'AR',
    switchToAr: 'العربية',
    switchToFr: 'Français',
    groupage: 'Groupage France-Maroc.',
    waLabel: 'Écrire sur WhatsApp',
    download: 'Télécharger',
    needNote: 'Texte',
    needParcels: 'Colis',
    parcelItem: 'Article / colis',
    parcelKg: 'kg',
    addParcel: 'Ajouter un colis',
    removeParcel: 'Retirer',
    estimated: 'Estimation',
    weightLabel: 'Poids estimé',
    corridorFr: 'France',
    corridorEs: 'Espagne',
    corridorMa: 'Maroc',
    corridorBoat: 'bateau',
  },
  ar: {
    offre: 'العرض',
    trajet: 'المسار',
    villes: 'المدن',
    agence: 'الوكالة',
    devis: 'عرض سعر',
    whatsapp: 'واتساب',
    langFr: 'FR',
    langAr: 'AR',
    switchToAr: 'العربية',
    switchToFr: 'Français',
    groupage: 'تجميع فرنسا المغرب.',
    waLabel: 'كتابة على واتساب',
    download: 'تحميل',
    needNote: 'نص',
    needParcels: 'طرود',
    parcelItem: 'صنف / طرد',
    parcelKg: 'كغ',
    addParcel: 'إضافة طرد',
    removeParcel: 'حذف',
    estimated: 'تقدير',
    weightLabel: 'الوزن التقديري',
    corridorFr: 'فرنسا',
    corridorEs: 'إسبانيا',
    corridorMa: 'المغرب',
    corridorBoat: 'قارب',
  },
} as const

export function t(lang: Lang) {
  return ui[lang]
}
